version: '3.7'

services:
    kashilog-sql-server:
      build:
        context: ./Databases
        dockerfile: DockerFile.local
      container_name: KashilogLocalDB
      ports:
        - 15331:1433
    kashilog-test-sql-server:
      build:
        context: ./Databases
        dockerfile: DockerFile.test
      container_name: KashilogTestDB
      ports:
        - 15332:1433

